apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-srv-klnavi
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - 'klnavi.de'
    secretName: public-srv-klnavi-dev-tls
  rules:
  - host: 'klnavi.de'
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: digitransit-ui-service
              port:
                number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-public-srv-klnavi
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - 'api.klnavi.de'
    secretName: api-public-srv-klnavi-tls
  rules:
  - host: 'api.klnavi.de'
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: opentripplanner-service
              port:
                number: 80
