apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

patches:
  - path: digitransit-ui-configmap.yml
    target:
      kind: ConfigMap
      name: digitransit-ui-config

resources:
  - ../../base
  - ./namespace.yml
  - ./ingress.yml
  - ./opentripplanner-standard.yml
  - ./opentripplanner-vision-impaired.yml
