apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opentripplanner-pvc
  namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: hcloud-volumes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentripplanner
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  minReadySeconds: 100
  template:
    metadata:
      labels:
        app: opentripplanner
    spec:
      initContainers:
        - name: download-files
          image: busybox
          command: 
            - /bin/sh
            - -c
            - |
              du -sh /var/opentripplanner/graph.obj
              wget -O /var/opentripplanner/otp-config.json https://raw.githubusercontent.com/goat-community/klnavi/main/opentripplanner/graph-main/otp-config.json
              wget -O /var/opentripplanner/router-config.json https://github.com/goat-community/klnavi/blob/main/opentripplanner/graph-main/router-config.json
              if [ ! -f /var/opentripplanner/graph_28_02_2024.obj ]; then 
                wget -O /var/opentripplanner/graph_28_02_2024.obj https://assets.plan4better.de/otp/klnavi/graph_28_02_2024.obj && cp /var/opentripplanner/graph_28_02_2024.obj /var/opentripplanner/graph.obj
              fi
          volumeMounts:
            - name: opentripplanner-data
              mountPath: /var/opentripplanner
      containers:
        - image: opentripplanner/opentripplanner:2.5.0_2024-02-29T13-29
          imagePullPolicy: IfNotPresent
          name: opentripplanner
          env:
          - name: JAVA_OPTS
            value: "-Xmx8G"
          args: ["--load"]
          volumeMounts:
            - name: opentripplanner-data
              mountPath: /var/opentripplanner
          ports:
            - containerPort: 8080
      volumes:
        - name: opentripplanner-data
          persistentVolumeClaim:
            claimName: opentripplanner-pvc