apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentripplanner
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  minReadySeconds: 100
  template:
    metadata:
      labels:
        app: opentripplanner
    spec:
      containers:
        - image: ghcr.io/bbnavi/opentripplaner-berlin-brandenburg:master
          imagePullPolicy: IfNotPresent
          name: opentripplanner
          resources:
            limits:
              cpu: "2"
              memory: "5000Mi"
          ports:
            - containerPort: 8080