apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-srv-klnavi-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - 'klnavi.dev.plan4better.de'
    secretName: public-srv-klnavi-dev-tls
  rules:
  - host: 'klnavi.dev.plan4better.de'
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: digitransit-ui-service
              port:
                number: 80
