apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

patches:
  - path: digitransit-ui-configmap.yml
    target:
      kind: ConfigMap
      name: digitransit-ui-config

  - path: opentripplanner-deployment.yml
    target:
      kind: Deployment
      name: opentripplanner

resources:
  - ../../base
  - ./namespace.yml
  - ./ingress.yml